when:
    - event: push

steps:
    - name: ci
      image: rust:slim-bookworm@sha256:8147f469458ff9dd26ac25c7dac505749db934088776a624869c01cd60581314
      commands:
        - cargo test
        - cd tests && cargo test
